language: node_js
sudo: false
node_js: "6.10.1"
install: for d in $TRAVIS_BUILD_DIR/functions/* ; do cd $d && npm install ; done ;
script: for d in $TRAVIS_BUILD_DIR/functions/* ; do cd $d && npm test || exit 1 ; done ;