language: node_js
sudo: false
node_js: "6.10.1"
cache:
  directories:
    - functions/*/node_modules
install: for d in $TRAVIS_BUILD_DIR/functions/* ; do cd $d && npm install ; done ;
script:
  - FAILED=0
  - for d in $TRAVIS_BUILD_DIR/functions/* ; do cd $d && npm test || FAILED=1 ; done ;
  - test $FAILED -eq 0
